"""Initial migration

Revision ID: 271f77fab100
Revises: 
Create Date: 2025-11-30 17:32:23.484439

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '271f77fab100'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('action_cards',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('action', sa.Enum('CHANGE', 'STEAL', 'REVEAL', 'EXCHANGE', 'INFO', 'CHANGE_SLOTS', name='actiontype'), nullable=False),
    sa.Column('value', sa.Enum('BIOLOGY', 'HEALTH', 'PROFESSION', 'HOBBY', 'PHOBIA', 'FACT', 'ITEM', 'ANY', 'BUNKER', 'CATASTROPHE', 'TEXT', 'ADD_SLOT', 'REMOVE_SLOT', name='actionvalue'), nullable=False),
    sa.Column('target', sa.Enum('ANY', 'ALL', 'SELF', 'NOT_SELF', 'NONE', name='actiontarget'), nullable=False),
    sa.Column('info', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('action', 'value', 'info', 'target', name='_action_value_info_target_uc')
    )
    op.create_table('attributes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('category', sa.Enum('BIOLOGY', 'HEALTH', 'PROFESSION', 'HOBBY', 'PHOBIA', 'FACT', 'ITEM', name='attributecategory'), nullable=False),
    sa.Column('value', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('category', 'value', name='_at_category_value_uc')
    )
    op.create_table('bunker_elements',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('category', sa.Enum('ITEM', 'ROOM', 'INFO', name='bunkerelementtype'), nullable=False),
    sa.Column('value', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('category', 'value', name='_be_category_value_uc')
    )
    op.create_table('catastrophes',
    sa.Column('id', sa.SmallInteger(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.String(length=512), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('games',
    sa.Column('id', sa.String(length=16), nullable=False),
    sa.Column('host_id', sa.String(length=128), nullable=False),
    sa.Column('status', sa.Enum('BeforeStart', 'Discussion', 'Voting', 'End', name='gamestatus'), nullable=False),
    sa.Column('count_to_kick', sa.SmallInteger(), nullable=False),
    sa.Column('places_count', sa.SmallInteger(), nullable=True),
    sa.Column('force_voting', sa.Boolean(), nullable=False),
    sa.Column('catastrophe_id', sa.SmallInteger(), nullable=True),
    sa.ForeignKeyConstraint(['catastrophe_id'], ['catastrophes.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('characters',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('game_id', sa.String(length=16), nullable=True),
    sa.Column('user_id', sa.String(length=128), nullable=False),
    sa.Column('status', sa.Enum('Alive', 'Protected', 'Kicked', name='characterstatus'), nullable=False),
    sa.Column('voted_for', sa.BigInteger(), nullable=True),
    sa.Column('needs_to_reveal', sa.Boolean(), nullable=False),
    sa.Column('attributes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['voted_for'], ['characters.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'game_id', name='_user_game_uc')
    )
    op.create_index('idx_characters_attributes_gin', 'characters', ['attributes'], unique=False, postgresql_using='gin')
    op.create_index(op.f('ix_characters_game_id'), 'characters', ['game_id'], unique=False)
    op.create_index(op.f('ix_characters_user_id'), 'characters', ['user_id'], unique=False)
    op.create_table('game_bunker_elements',
    sa.Column('game_id', sa.String(length=16), nullable=False),
    sa.Column('bunker_element_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['bunker_element_id'], ['bunker_elements.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('game_id', 'bunker_element_id')
    )
    op.create_table('character_action_cards',
    sa.Column('character_id', sa.BigInteger(), nullable=False),
    sa.Column('action_card_id', sa.Integer(), nullable=False),
    sa.Column('is_used', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['action_card_id'], ['action_cards.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('character_id', 'action_card_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('character_action_cards')
    op.drop_table('game_bunker_elements')
    op.drop_index(op.f('ix_characters_user_id'), table_name='characters')
    op.drop_index(op.f('ix_characters_game_id'), table_name='characters')
    op.drop_index('idx_characters_attributes_gin', table_name='characters', postgresql_using='gin')
    op.drop_table('characters')
    op.drop_table('games')
    op.drop_table('catastrophes')
    op.drop_table('bunker_elements')
    op.drop_table('attributes')
    op.drop_table('action_cards')
    # ### end Alembic commands ###
